site_name: HiWa Cookbook
#site_url: https://github.com/hiwa-house/recipes

theme:
    name: material

#nav:
#    - Home: index.md

markdown_extensions:

    # Python Markdown
    - meta
    - toc:
        permalink: true

    # Python Markdown Extensions
    - pymdownx.highlight
    - pymdownx.tasklist:
        clickable_checkbox: true
    - pymdownx.magiclink:
        hide_protocol: true
