site_name: HiWa Cookbook
#site_url: https://github.com/hiwa-house/recipes

theme:
    name: material
    icon: 
        logo: material/chef-hat
    favicon: apple-touch-icon.png
    features:
#        - navigation.expand
        - navigation.instant

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    # Python Markdown
    - admonition
    - attr_list
#    - md_in_html
    - meta
    - toc:
        permalink: true

    # Python Markdown Extensions
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        clickable_checkbox: true
