site_name: HiWa Cookbook
#site_url: https://github.com/hiwa-house/recipes

theme:
    name: material
    icon: 
        logo: material/chef-hat
    favicon: docs/chef-hat.png

#nav:
#    - Home: index.md

markdown_extensions:

    # Python Markdown
    - admonition
    - meta
    - toc:
        permalink: true

    # Python Markdown Extensions
    - pymdownx.highlight
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tasklist:
        clickable_checkbox: true
    - pymdownx.magiclink:
        hide_protocol: true
